project:
  type: website
  output-dir: docs

website:
  title: "Shen Rothermel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - miniproject1.qmd
      - miniproject2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

